// src/pages/Home.vue
<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue'
import Main from '@/components/Main.vue'
import Profile from '@/components/Profile.vue'
import Skile from '@/components/Skile.vue'
import Project from '@/components/Project.vue'
import Career from '@/components/Career.vue'
import Stars from '@/components/Stars.vue'
import ScrollToTop from '@/components/ScrollToTop.vue'

import { registerScrollWatcher, unregisterScrollWatcher } from '@/utils/useScroll'

const main = ref<HTMLElement | null>(null)
const carreers = ref<HTMLElement | null>(null)
const projects = ref<HTMLElement | null>(null)
const carreerActive = ref(false)
const projectActive = ref(false)
const topActive = ref(false)

onMounted(() => {
  // Main 섹션을 벗어나면 ScrollToTop 표시
  registerScrollWatcher({
    elementRef: main,
    thresholds: [
      {
        threshold: 0,
        callback: (isActive) => {
          topActive.value = isActive
        }
      }
    ]
  })

  // Career 섹션 기준 배경색 변경 (어두운 → 흰색)
  registerScrollWatcher({
    elementRef: carreers,
    thresholds: [
      {
        threshold: -200,
        callback: (isActive) => {
          carreerActive.value = isActive
        }
      }
    ]
  })

  // Project 섹션 기준 배경색 변경 (흰색 → 어두운)
  registerScrollWatcher({
    elementRef: projects,
    thresholds: [
      {
        threshold: -200,
        callback: (isActive) => {
          projectActive.value = isActive
        }
      }
    ]
  })
})

onBeforeUnmount(() => {
  unregisterScrollWatcher(main)
  unregisterScrollWatcher(carreers)
  unregisterScrollWatcher(projects)
})
</script>

<template>
  <div class="relative">
    <div
      class="fixed inset-0 -z-10 transition-colors duration-500"
      :class="projectActive ? 'bg-black' : carreerActive ? 'bg-white' : 'bg-[#222831]'"
    >
      <Stars />
    </div>

    <div class="relative flex flex-col">
      <section ref="main" class="flex min-h-screen w-full"><Main  /></section>
      <section class="flex min-h-screen w-full"><Profile  /></section>
      <section class="flex min-h-screen w-full"><Skile  /></section>
      <section ref="carreers" class="flex min-h-screen w-full"><Career  /></section>
      <section ref="projects" class="flex min-h-screen w-full"><Project :active="projectActive" /></section>
      <ScrollToTop :active="topActive" />
    </div>
  </div>
</template>

// src/components/Home.tsx
'use client'

import { useState, useRef, useEffect } from 'react'

import MainSection from '@/components/Main'
import Profile from '@/components/Profile'
import Skile from '@/components/Skile'
import Project from '@/components/Project'
import Career from '@/components/Career'
import Stars from '@/components/Stars'
import ScrollToTop from '@/components/ScrollToTop'
import { registerScrollWatcher, unregisterScrollWatcher } from '@/utils/useScroll'

export default function Home() {
  const main = useRef<HTMLElement>(null)
  const careers = useRef<HTMLElement>(null)
  const projects = useRef<HTMLElement>(null)
  const [careerActive, setCareerActive] = useState(false)
  const [projectActive, setProjectActive] = useState(false)
  const [topActive, setTopActive] = useState(false)

  useEffect(() => {
    registerScrollWatcher({
      elementRef: main,
      thresholds: [{ threshold: 0, callback: (isActive) => setTopActive(isActive) }]
    })
    registerScrollWatcher({
      elementRef: careers,
      thresholds: [{ threshold: -200, callback: (isActive) => setCareerActive(isActive) }]
    })
    registerScrollWatcher({
      elementRef: projects,
      thresholds: [{ threshold: -200, callback: (isActive) => setProjectActive(isActive) }]
    })
    return () => {
      unregisterScrollWatcher(main)
      unregisterScrollWatcher(careers)
      unregisterScrollWatcher(projects)
    }
  }, [])

  return (
    <div className="relative">
      <div className={`fixed inset-0 -z-10 transition-colors duration-500 ${
        projectActive ? 'bg-black' : careerActive ? 'bg-white' : 'bg-[#222831]'
      }`}>
        <Stars />
      </div>
      <div className="relative flex flex-col">
        <section ref={main} className="flex min-h-screen w-full"><MainSection /></section>
        <section className="flex min-h-screen w-full"><Profile /></section>
        <section className="flex min-h-screen w-full"><Skile /></section>
        <section ref={careers} className="flex min-h-screen w-full"><Career /></section>
        <section ref={projects} className="flex min-h-screen w-full"><Project active={projectActive} /></section>
        <ScrollToTop active={topActive} />
      </div>
    </div>
  )
}
